# Fourier Tables {#fourier-table}

## Continuous-Time Fourier Transforms {#ctft}

\[ G(f) = \int_{-\infty}^\infty g(t) e^{-j2\pi f t}\,dt,\ \ -\infty < f < \infty \]

| Time-Domain $g(t)$ | Frequency-Domain $G(f) = \mathscr{F}[g(t)]$ | 
|:---|:---|
$1$ | $\delta(f)$ |
$u(t) \overset{\text{def}}{=} \begin{cases} 1 & t \geq 0 \\ 0 & t < 0 \end{cases}$ | $\displaystyle\frac{1}{2}\delta(f) + \frac{1}{j2\pi f}$ |
$\cos(2\pi f_0 t)$ | $\frac{1}{2}(\delta(f - f_0) + \delta(f + f_0))$  |
$\sin(2\pi f_0 t)$ | $\frac{1}{2j}(\delta(f - f_0) - \delta(f + f_0))$  |
$e^{-t}u(t)$ | $\displaystyle\frac{1}{1 + j2\pi f}$ |
$e^{-|t|}$ | $\displaystyle\frac{2}{1 + (2\pi f)^2}$ |
$e^{-\pi t^2}$ | $e^{-\pi f^2}$ |
$\text{rect}(t) \overset{\text{def}}{=} \begin{cases} 1 & |t| \leq 0.5 \\ 0 & |t| > 0.5 \end{cases}$ | $\displaystyle\text{sinc}(f) \overset{\text{def}}{=} \frac{\sin(\pi f)}{\pi f}$ |
$\text{tri}(t) \overset{\text{def}}{=} \begin{cases} 1 - |t| & |t| \leq 1 \\ 0 & |t| > 1 \end{cases}$ | $\text{sinc}^2(f)$ | 


## Discrete-Time Fourier Transforms {#dtft}

Note that $f$ here denotes _normalized frequency_ (cycles/sample).
\[ G(f) = \sum_{n=-\infty}^\infty g[n] e^{-j2\pi f n},\ \ -\frac{1}{2} < f < \frac{1}{2} \]

| Time-Domain $g[n]$ | Frequency-Domain $G(f) = \mathscr{F}[g[n]]$ | Restrictions |
|:--|:---|:--|
| $1$ | $\delta(f)$ |
| $\delta[n]$ | $1$ |
| $\cos(2\pi f_0 n)$ | $\frac{1}{2}(\delta(f - f_0) + \delta(f + f_0))$ | $-\frac{1}{2} < f_0 < \frac{1}{2}$ | 
| $\sin(2\pi f_0 n)$ | $\frac{1}{2j}(\delta(f - f_0) - \delta(f + f_0))$ | $-\frac{1}{2} < f_0 < \frac{1}{2}$ | 
| $\alpha^{|n|}$ |$\displaystyle\frac{1 - \alpha^{2}}{1 + \alpha^{2} - 2\alpha \cos(2\pi f)}$ | $|\alpha| < 1$ |
| $\alpha^{n} u[n]$ | $\displaystyle\frac{1}{1 - \alpha e^{-j2\pi f}}$ | $|\alpha| < 1$ |


## Fourier Properties {#fourier-properties}

Suppose $g$, $g_1$, and $g_2$ are time-domain signals with Fourier transforms $G$, $G_1$, and $G_2$, respectively.

Property | When It Applies | Time-Domain | | Frequency-Domain |
|:---|:---:|----:|:-:|:----|
Linearity | continuous-time, discrete-time | $a g_1(t) + b g_2(t)$ | $\overset{\mathscr{F}}{\longleftrightarrow}$ | $a G_1(f) + b G_2(f)$ |
Scaling | continuous-time only | $g(at)$ | $\overset{\mathscr{F}}{\longleftrightarrow}$ | $\frac{1}{a} G\left(\frac{f}{a}\right)$ |
Shifting | continuous-time, discrete-time  | $g(t + b)$ | $\overset{\mathscr{F}}{\longleftrightarrow}$ | $G(f) e^{j2\pi b f}$ |
Convolution | continuous-time, discrete-time | $(g_1 * g_2)(t)$ | $\overset{\mathscr{F}}{\longleftrightarrow}$ | $G_1(f) \cdot G_2(f)$ |
Reversal | continuous-time, discrete-time | $g(-t)$ | $\overset{\mathscr{F}}{\longleftrightarrow}$ | $G(-f)$ |
DC Offset | continuous-time, discrete-time | $\int_{-\infty}^\infty g(t)\,dt$ | $\overset{\mathscr{F}}{\longleftrightarrow}$  | $G(0)$ |
