# Hypergeometric Distribution {#hypergeometric}

## Motivating Example {-}

The Powerball is a lottery game that runs in 45 U.S. states. When you purchase a lottery ticket, you choose $5$ numbers from $1$ to $69$, and a sixth number from $1$ to $26$. This ball is known as the Powerball.

Drawings occur on Wednesday and Saturday nights, where $5$ white balls are chosen **without replacement** with labels from $1$ to $69$, and a single red ball is chosen with labels ranging from $1$ to $26$. Since the red ball is chosen from a different batch, it is possible for the red Powerball to match a number drawn from the white balls, but it is not possible for two of the five chosen white balls to have the same number.

To win the jackpot, (which has reached over $1.5 billion at its peak), you must match your five chosen numbers with the labels of the five white balls drawn, as well as picking the right number for the red Powerball. For the five white balls, they do not have to be chosen in the correct order that they were drawn. 

What is the probability that you go and buy a ticket, that ends up winning the powerball Jackpot?

First of all, we have to choose the right $5$ white balls labeled $1$ through $69$. To count the ways that this can happen, we can use combinations. We know that we have to have our $5$ chosen numbers drawn, and the remaining $64$ white balls cannot be chosen, which can be represented by $\binom{5}{5} \cdot \binom{64}{0}$. We must then divide this by the number of possible ways to draw $5$ numbers from $69$ possible, so this turns out to be $$\dfrac{\binom{5}{5} \cdot \binom{64}{0}}{\binom{69}{5}} = \dfrac{1}{11238513}$$. 

Lastly, we have to multiply this by the chance that we choose the right number for the red Powerball, which is $\dfrac{1}{26}$. Our final probability turns out to be $$\dfrac{1}{11238513 \cdot 26} = \dfrac{1}{292201338}$$, or about a $1$ in $292$ million chance that you win the Powerball.


------

## Theory {-}

```{definition}
The Hypergeometric distribution is defined as
\begin{equation}
P(X = x) = \dfrac{\binom{k}{x}\binom{N-k}{n-x}}{\binom{N}{n}}
(\#eq:hypergeometric)
\end{equation}
  
Where $k$ is the number of successes in the population, $x$ is the number of successes in the sample, $N$ is the number of items in the population, and $n$ is the number of items drawn from the sample.

```

We can also use sums of the hypergeometric formula to calculate probabilities such as $P(X \le x)$, the c.d.f of $X$

$$P(X \le x) = \sum_{i=0}^x\dfrac{\binom{k}{x}\binom{N-k}{n-x}}{\binom{N}{n}}$$

Similarly, we can find $P(X \ge x)$

$$P(X \ge x) = \sum_{i=x}^n\dfrac{\binom{k}{x}\binom{N-k}{n-x}}{\binom{N}{n}}$$

## Worked Examples {-}

1. Your state proposes a new lottery game in which you select $6$ numbers from $1$ to $15$. When it is time to draw, the lottery selects $8$ numbers, and prizes are won if at least $4$ of the $6$ numbers that you picked are part of the $8$ numbers that the lottery drew. What is the probability that a randomly selected ticket wins a prize?

This is a hypergeometric distributions with parameters $N=15, n=8,$ and $k=6$. Therefore, the resulting probability becomes

$$\dfrac{\binom{6}{4}\binom{15-6}{8-4}}{\binom{15}{8}} + \dfrac{\binom{6}{5}\binom{15-6}{8-5}}{\binom{15}{8}} + \dfrac{\binom{6}{6}\binom{15-6}{8-6}}{\binom{15}{8}} = 0.3776$$

------

2. In poker, a three-of-a-kind is when your hand consists of exactly $3$ cards of the same rank (Ex: $\{5, 8, J, J, J\}$ or $\{7, 7, 7, K, A\}$). What is the probability that you are dealt $5$ cards, and you have a three-of-a-kind?

The probability that we have $3$ cards of a specific rank out of $5$ cards that are dealt is $$\dfrac{\binom{4}{3}\binom{48}{2}}{\binom{52}{5}} = 0.00174$$

But we have $13$ ranks of cards in our deck, so this probability becomes

$$13 \cdot \dfrac{\binom{4}{3}\binom{48}{2}}{\binom{52}{5}} = 0.02256$$

So there is a $2.256\%$ chance that you are dealt a three-of-a-kind.

------


## Exercises {-}

1. In Texas Hold'em, you are dealt $2$ cards in your hand, and share $5$ cards in the middle of the table with the other players. A flush occurs when you have at least $5$ cards of the same suit out of the $7$ total cards. The deck is shuffled between hands, so that the probability you obtain a flush is independent from hand to hand. What is the probability that you get at least $1$ flush in $10$ hands of Texas Hold'em?

------

2. There are $25$ coins in a jar. $15$ are quarters, $7$ are dimes, and $3$ are pennies. Each time you reach in the jar, your are equally likely to pick any of the coins in the jar. What is the minimum number of times you must reach in the jar to have at least a $50\%$ chance of getting all $3$ pennies.

------

3. You are enrolled in $3$ courses this quarter, and the breakdown of majors by class is as follows:

Class 1: $17$ Statistics Majors and $13$ Math Majors

Class 2: $4$ Statistics Majors and $6$ Math Majors

Class 3: $11$ Statistics Majors and $9$ Math Majors

You pick one of your $3$ classes at random, and then choose a random sample of $20\%$ students from that class. What is the probability that the number of Statistics majors in your sample is equal to the number of Math majors in your sample?